export const buyTestimonialData = [
  {
    id: 1,
    name: "Dheeraj Singh",
    location: "Noida",
    carName: "Maruti Suzuki WagonR",
    stars: 5,
    text: "I had a very positive experience at Unifcars. Their used car selling process was so smooth and efficient. Thanks for their excellent planning and delivery.",
  },
  {
    id: 2,
    name: "Rekha Sharma",
    location: "Greater Noida",
    carName: "Tata Punch",
    stars: 5,
    text: "Recently, I sold my car on Unfi Cars. The process was very easy with less documentation. Plus, I have received quick payment too. Their customer support was excellent.",
  },
  {
    id: 3,
    name: "Aman Gupta",
    location: "East Delhi",
    carName: "Maruti Suzuki Swift",
    stars: 5,
    text: "Unifi Cars made the car selling process very easy. They provided quick payments, and their staff were also very supportive throughout the entire selling process.",
  },
  {
    id: 4,
    name: "Piyush Jain",
    location: "Delhi",
    carName: "Honda Amaze",
    stars: 5,
    text: "Recently, I sold my car on Unfi Cars. It was a great experience. They offer a smooth and transparent process, and I got my payment instantly. I am totally justified with their service.",
  },
  {
    id: 5,
    name: "Sambhav Jain",
    location: "New Delhi",
    carName: "Maruti Suzuki Baleno",
    stars: 5,
    text: "Selling my car to Unifi Cars was an amazing experience for me. The process of selling the car was transparent. I highly recommend their service.",
  },
];

export const sellTestimonialData = [
  {
    id: 1,
    name: "Dheeraj Singh",
    location: "Noida",
    carName: "Maruti Suzuki WagonR",
    stars: 5,
    text: "I had a very positive experience at Unifcars. Their used car selling process was so smooth and efficient. Thanks for their excellent planning and delivery.",
  },
  {
    id: 2,
    name: "Rekha Sharma",
    location: "Greater Noida",
    carName: "Tata Punch",
    stars: 5,
    text: "Recently, I sold my car on Unfi Cars. The process was very easy with less documentation. Plus, I have received quick payment too. Their customer support was excellent.",
  },
  {
    id: 3,
    name: "Aman Gupta",
    location: "East Delhi",
    carName: "Maruti Suzuki Swift",
    stars: 5,
    text: "Unifi Cars made the car selling process very easy. They provided quick payments, and their staff were also very supportive throughout the entire selling process.",
  },
  {
    id: 4,
    name: "Piyush Jain",
    location: "Delhi",
    carName: "Honda Amaze",
    stars: 5,
    text: "Recently, I sold my car on Unfi Cars. It was a great experience. They offer a smooth and transparent process, and I got my payment instantly. I am totally justified with their service.",
  },
  {
    id: 5,
    name: "Sambhav Jain",
    location: "New Delhi",
    carName: "Maruti Suzuki Baleno",
    stars: 5,
    text: "Selling my car to Unifi Cars was an amazing experience for me. The process of selling the car was transparent. I highly recommend their service.",
  },
];
