export const buyTestimonialData = [
  {
    id: 1,
    name: "Raghav Sharma",
    location: "New Delhi",
    carName: "Bought Honda City",
    stars: 5,
    text: "I have recently purchased a used car from Unifi Cars. Their customer service and delivery process were just amazing.",
  },
  {
    id: 2,
    name: "Tarun Mittal",
    location: "Gurugram",
    carName: "Bought Maruti Suzuki Swift",
    stars: 5,
    text: "I visited Unifi Cars to buy a car, and now I am fully satisfied with my car-buying process. The process is hassle-free. I am happy with their service.",
  },
  {
    id: 3,
    name: "Ashok Kapoor",
    location: "Delhi NCR",
    carName: "Bought Hyundai i10",
    stars: 5,
    text: "I bought my first car from them. The deal was fairly priced, and their all-used car is in good condition, and their team was very supportive too.",
  },
  {
    id: 4,
    name: "Bhumika",
    location: "Delhi NCR",
    carName: "Bought Hyundai i10",
    stars: 5,
    text: "I'm happy with the car I bought. It's in excellent condition and very comfortable. I found their car buying process smooth.",
  },
  {
    id: 5,
    name: "Rohan Rajput",
    location: "Ghaziabad",
    carName: "Bought Hyundai i10",
    stars: 5,
    text: "The car I bought is in very good condition and comfortable, too. I really like their customer service. Moreover, I found fair pricing here.",
  },
];

export const sellTestimonialData = [
  {
    id: 1,
    name: "Dheeraj Singh",
    location: "Noida",
    carName: "Sold Maruti Suzuki WagonR",
    stars: 5,
    text: "I had a very positive experience at Unifcars. Their used car selling process was so smooth and efficient. Thanks for their excellent planning and delivery.",
  },
  {
    id: 2,
    name: "Rekha Sharma",
    location: "Greater Noida",
    carName: "Sold Tata Punch",
    stars: 5,
    text: "Recently, I sold my car on Unfi Cars. The process was very easy with less documentation. Plus, I have received quick payment too. Their customer support was excellent.",
  },
  {
    id: 3,
    name: "Aman Gupta",
    location: "East Delhi",
    carName: "Sold Maruti Suzuki Swift",
    stars: 5,
    text: "Unifi Cars made the car selling process very easy. They provided quick payments, and their staff were also very supportive throughout the entire selling process.",
  },
  {
    id: 4,
    name: "Piyush Jain",
    location: "Delhi",
    carName: "Sold Honda Amaze",
    stars: 5,
    text: "Recently, I sold my car on Unfi Cars. It was a great experience. They offer a smooth and transparent process, and I got my payment instantly. I am totally justified with their service.",
  },
  {
    id: 5,
    name: "Sambhav Jain",
    location: "New Delhi",
    carName: "Sold Maruti Suzuki Baleno",
    stars: 5,
    text: "Selling my car to Unifi Cars was an amazing experience for me. The process of selling the car was transparent. I highly recommend their service.",
  },
];

export const inspectionTestimonialData = [
  {
    id: 1,
    name: "Priti Singh",
    location: "Ghaziabad",
    carName: "Hyundai i20",
    stars: 5,
    text: "Unifi Cars provided excellent service with a perfect inspection process and good customer support. I highly recommend Unifi Cars to others.",
  },
  {
    id: 2,
    name: "Prince Pal",
    location: "Noida",
    carName: "Mahindra Scorpio",
    stars: 5,
    text: "The Unifi Cars inspection process is just so good, and their staff was also so helpful and friendly. Overall, it was a nice experience with them!",
  },
  {
    id: 3,
    name: "Armaan",
    location: "Delhi",
    carName: "Honda City",
    stars: 5,
    text: "UnifiCars makes me stress-free with their inspection service and well-maintained used vehicles. I will definitely recommend Unifi Cars to others!",
  },
  {
    id: 4,
    name: "Haider Ali",
    location: "New Delhi",
    carName: "Maruti Suzuki Breeza",
    stars: 5,
    text: "Unifi Cars provided quick, easy, and reliable Inspection Process. That exceeded all my expectations for inspection and used car buy-sell process as they inspected car with 210 checkpoints.",
  },
  {
    id: 5,
    name: "Ashish Kumar",
    location: "Greater Noida",
    carName: "Tata Tiago",
    stars: 5,
    text: "Unifi Cars offers great prices, superb customer service, and a smooth inspection process. Now they are my first choice for used car deals.",
  },
];

// export const dealerTestimonialData = [
//   {
//     id: 1,
//     name: "SI MOTORS",
//     location: "Noida",
//     stars: 5,
//     text: "Excellent customer service from inquiry till the final settlement of the amount, everything is super easygoing.",
//   },
//   {
//     id: 2,
//     name: "Geeta",
//     location: "Gujarat",
//     stars: 4,
//     text: "While selling the cars via Unifi cars you don't need to be restless as the whole process is very transparent and prompt.",
//   },
//   {
//     id: 3,
//     name: "Snigdha",
//     location: "Delhi",
//     stars: 5,
//     text: "The entire process was completely online, and after a few hours, we received the Car at home as well.",
//   },
//   {
//     id: 4,
//     name: "Partha",
//     location: "Gurgaon",
//     stars: 5,
//     text: "Delighted with the behavior of staff members of Unifi Cars, very efficient, customer friendly, soft-spoken, and patient staff.",
//   },
//   {
//     id: 5,
//     name: "Snigdha",
//     location: "Delhi",
//     stars: 5,
//     text: "I had an awesome and seamless experience in selling my Maruti Suzuki ciaz with Unifi Cars they offer the best deals.",
//   },
//   {
//     id: 6,
//     name: "Geeta",
//     location: "Gujarat",
//     stars: 5,
//     text: "All over the interaction was extremely great and I highly recommend Unifi Cars for selling the cars.",
//   },
// ];

export const dealerTestimonialData = [
  {
    id: 1,
    name: "SI MOTORS",
    location: "Noida",
    stars: 5,
    text: "I recently purchased a car from Quick Buy. The vehicle is in excellent condition and truly value for money.",
  },
  {
    id: 2,
    name: "AS TRADING",
    location: "Jaipur",
    stars: 4,
    text: "Our dealership's inventory has improved since we started sourcing cars from Unificars. The car is in good condition.",
  },
  {
    id: 3,
    name: "GIANI MOTORS",
    location: "Gujarat",
    stars: 5,
    text: "As a dealer, finding reliable sources for quality cars is very crucial, and Unificars has never disappointed us.",
  },
  {
    id: 4,
    name: "GM MOTORS",
    location: "Faridabad",
    stars: 5,
    text: "The bidding system at unificars is the best system. We have won numerous cars that are well maintained.",
  },
  {
    id: 5,
    name: "EXPART AUTOMOBILE",
    location: "Delhi",
    stars: 5,
    text: "Customer service at Unificars is Best. From the moment we inquired till the settlement the process was smooth.",
  },
  {
    id: 6,
    name: "NAWAJISH MOTORS",
    location: "Mumbai",
    stars: 5,
    text: "Finding a well-maintained car at a great price was easy with Quick Buy, and the staff were incredibly helpful as well.",
  },
];
